apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 1200
  replicas: {{ .Values.agentCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: In
                    values:
                      - {{ .Values.windowsDeployAgentsNodePoolLabel }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.deploymentName }}
                topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: {{ .Values.deploymentName }}
        image: {{ .Values.PublicAcrName }}.azurecr.io/{{ .Values.ContainerImageName }}: {{ .Values.ImageTag }}
        command: ["powershell"]
        args: ["./start.ps1"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 700m
            memory: 3Gi
          requests:
            cpu: 270m
            memory: 256Mi
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azp
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azp
                key: AZP_TOKEN
          - name: AZP_POOL
            value: {{ .Values.azureDevopsAgentPool }}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - mountPath: /azptmp
          name: azp-tmp-volume
        - mountPath: /azp/agent/_work/_tasks
          name: agent-cache-{{ .Values.type }}
        - mountPath: /azp/agent/_work/_tool
          name: agent-cache-{{ .Values.type }}
      tolerations:
        - key: agent-os
          operator: Equal
          value: windows
          effect: NoSchedule
      volumes:
      - name: azp-tmp-volume
        emptyDir:
          sizeLimit: 30Gi
      - name: agent-cache-{{ .Values.type }}
        persistentVolumeClaim:
          claimName: agent-cache-{{ .Values.type }}
