{{ if .Values.persistentVolumeClaim.enable }}
{{ range $i := until (divf $.Values.agentCount 4 | ceil | int) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-cache-{{ $i }}
  namespace: {{ $.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium2-disk-sc
  resources:
    requests:
      storage: {{ $.Values.persistentVolumeClaim.storage }}
{{ end -}}
{{ end -}}
