{{ if .Values.storageClass.enable }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
parameters:
  cachingMode: {{ .Values.storageClass.cachingMode }}
  skuName: {{ .Values.storageClass.skuName }}
  DiskIOPSReadWrite: "{{ .Values.storageClass.DiskIOPSReadWrite }}"
  DiskMBpsReadWrite: "{{ .Values.storageClass.DiskMBpsReadWrite }}"
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
{{ end -}}
