trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Linux/Base/*"
    exclude:
      - "*"

resources:
  repositories:
    - repository: self
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/0.4.12
      endpoint: SkillsFundingAgency

schedules:
- cron: "0 6 * * Tue"
  displayName: Weekly Tuesday morning build
  branches:
    include:
    - master
  always: true

pr: none

pool:
  name: DAS - Continuous Integration Agents

variables:
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-base-agent

steps:
- template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
  parameters:
    ContainerRegistryName: $(PublicAcrName)
    ServiceConnection: SFA-DIG-Prod-ARM
    ImageName: $(ContainerImageName)
    WorkingDirectory: $(Build.SourcesDirectory)/Linux/Base

