trigger:
  batch: true
  branches:
    include:
    - "*"
  paths:
    include:
    - "Windows/Deploy/*"
    exclude:
    - "*"

pr: 
  paths:
    include:
    - "Windows/Deploy/*"

pool:
  name: DAS - Continuous Integration Agents

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.13
    endpoint: SkillsFundingAgency

variables:
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-deploy-agent-win

steps:
- template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
  parameters:
    ContainerRegistryName: $(PublicAcrName)
    ServiceConnection: SFA-DIG-Prod-ARM
    ImageName: $(ContainerImageName)
    BranchToCreateLatestTag: master
    Platform: windows
    WorkingDirectory: $(Build.SourcesDirectory)/Windows/Deploy

- task: CopyFiles@2
  displayName: "Copy Files to: $(build.artifactstagingdirectory)"
  inputs:
    Contents: |
      Windows/Deploy/manifest.yml
    TargetFolder: "$(build.artifactstagingdirectory)/publish"
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifact"
  inputs:
    PathtoPublish: "$(build.artifactstagingdirectory)/publish"
