apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-pipelines-deploy-agent-win
  namespace: __agentNameSpace__
spec:
  replicas: __agentCount__
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: azure-pipelines-deploy-agent-win
  template:
    metadata:
      labels:
        app: azure-pipelines-deploy-agent-win
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: In
                    values:
                      - __nodePoolLabel__
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - azure-pipelines-deploy-agent-win
                topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: azure-pipelines-deploy-agent-win
        image: __PublicAcrName__.azurecr.io/__ContainerImageName__:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 256Mi
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azp
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azp
                key: AZP_TOKEN
          - name: AZP_POOL
            value: DAS - Continuous Deployment Agents
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: task-cache
            mountPath: /azp/agent/_work/_tasks
      tolerations:
        - key: agent-os
          operator: Equal
          value: windows
          effect: NoSchedule
      volumes:
        - name: task-cache
          hostPath:
            path: /azp/agent/_work/_tasks
            type: DirectoryOrCreate
