trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Linux/Deploy/Image"
    exclude:
      - "*"

pr:
  paths:
    include:
      - "Linux/Deploy/Image"

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SFA

schedules:
- cron: "0 5 * * Wed"
  displayName: Weekly Wednesday morning run
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

variables:
- group : Release Management Resources

jobs:
- job: ImageBuild
  timeoutInMinutes: 120
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
    parameters:
      ContainerRegistryName: $(PublicAcrName)
      ServiceConnection: SFA-DIG-Prod-ARM
      ImageName: azure-pipelines-deploy-agent-linux
      WorkingDirectory: Linux/Deploy/Image
      BranchToCreateLatestTag: master
