trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Linux/Ubuntu-20/Base/*"
    exclude:
      - "*"

schedules:
- cron: "0 6 * * Tue"
  displayName: Weekly Tuesday morning build
  branches:
    include:
    - master
  always: true

pr: none

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.23
    endpoint: SFA

pool:
  vmImage: ubuntu-latest

variables:
- group : Release Management Resources

steps:
  - script: sudo apt-get remove azure-cli
    
  - script: curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
    
  - script: echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
    
  - script: sudo apt-get update
    
  - script: sudo apt-get install azure-cli
  
  - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
    parameters:
      ContainerRegistryName: $(PublicAcrName)
      ServiceConnection: SFA-DIG-Prod-ARM
      ImageName: azure-pipelines-base-build-agent-ubuntu-20
      WorkingDirectory: Linux/Ubuntu-20/Base
      BranchToCreateLatestTag: DASD-8851-ubuntu-18-20-build-agents.2