trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Linux/Deploy/Deployment"
    exclude:
      - "*"

pr:
  paths:
    include:
      - "Linux/Deploy/Deployment"

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SFA
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.0.6
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: image-build
    source: das-azure-pipelines-agents-linux-deploy (Image Build)
    branch: master
    trigger:
      branches:
        - master

pool:
  name: DAS - Continuous Integration Agents

variables:
- group: RELEASE das-azure-pipelines-agent
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-deploy-agent-linux
- name: ImageTag
  value: $(resources.pipeline.image-build.runName)

stages:
  - stage: DeployDev
    variables:
    - group: Dev Management Resources
    - name: AgentCount
      value: 6
    - name: AzureDevopsAgentPool
      value: DAS - Continuous Deployment Beta
    - name: DeploymentName
      value: beta-azure-pipelines-deploy-agent-linux
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      steps:
        - template: /pipeline-templates/step/deploy.yml
          parameters:
            VerifyDeployment: true
            Directory: Linux/Deploy/Deployment
            AzureServiceConnection: SFA-DAS-DevTest-ARM
  - stage: DeployProd
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables['resources.pipeline.image-build.sourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
    - group: PROD Management Resources
    - name: AgentCount
      value: 6
    - name: AzureDevopsAgentPool
      value: DAS - Continuous Deployment Linux
    - name: DeploymentName
      value: azure-pipelines-deploy-agent-linux
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      steps:
        - template: /pipeline-templates/step/deploy.yml
          parameters:
            VerifyDeployment: true
            Directory: Linux/Deploy/Deployment
            AzureServiceConnection: SFA-DIG-Prod-ARM

