trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Windows/Deploy/Deployment"
    exclude:
      - "*"

pr:
  paths:
    include:
      - "Windows/Deploy/Deployment"

pool:
  name: DAS - Continuous Integration Agents

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.73
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: image-build
    source: das-azure-pipelines-agents-win-deploy (Image Build)
    branch: DASD-11212-Set-CPU/memory
    trigger:
      branches:
        - master

variables:
- group: RELEASE das-azure-pipelines-agent
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-deploy-agent-win
- name: ImageTag
  value: $(resources.pipeline.image-build.runName)

stages:
  - stage: DeployPreProd
    variables:
    - group: PreProd Management Resources
    - name: MinAgentCount
      value: 0
    - name: MaxAgentCount
      value: 8
    - name: AzureDevopsAgentPool
      value: DAS - Continuous Deployment Beta
    - name: DeploymentName
      value: beta-azure-pipelines-deploy-agent-win
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      steps:
        - template: /pipeline-templates/step/deploy.yml
          parameters:
            VerifyDeployment: true
            Directory: $(System.DefaultWorkingDirectory)/Windows/Deploy/Deployment
            AzureServiceConnection: SFA-DIG-PreProd-ARM
  - stage: DeployProd
    dependsOn: DeployPreProd
    condition: and(succeeded(), eq(variables['resources.pipeline.image-build.sourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
    - group: PROD Management Resources
    - name: MinAgentCount
      value: 2
    - name: MaxAgentCount
      value: 20 
    - name: AzureDevopsAgentPool
      value: DAS - Continuous Deployment Agents
    - name: DeploymentName
      value: azure-pipelines-deploy-agent-win
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      steps:
        - template: /pipeline-templates/step/deploy.yml
          parameters:
            VerifyDeployment: true
            Directory: $(System.DefaultWorkingDirectory)/Windows/Deploy/Deployment
            AzureServiceConnection: SFA-DIG-Prod-ARM








