trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Windows/Deploy/Deployment"
    exclude:
      - "*"

pr:
  paths:
    include:
      - "Windows/Deploy/Deployment"

pool:
  name: DAS - Continuous Integration Agents

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.73
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: image-build
    source: das-azure-pipelines-agents-win-deploy (Image Build)
    branch: master
    trigger:
      branches:
        - master

variables:
- group: RELEASE das-azure-pipelines-agent
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-deploy-agent-win
- name: ImageTag
  value: $(resources.pipeline.image-build.runName)
- name: ValueFile
  value: Windows/Deploy/Deployment/values.yaml

stages:
  - stage: DeployPreProd
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      variables:
      - group: PreProd Management Resources
      steps:
        - template: /pipeline-templates/step/deploy-helm.yml
          parameters:
            AgentCount: 2
            AzureDevopsAgentPool: '"DAS - Continuous Deployment Beta"'
            AzureServiceConnection: SFA-DIG-PreProd-ARM
            ContainerImageName: ${{ variables.ContainerImageName }}
            DeploymentName: beta-azure-pipelines-deploy-agent-win
            ImageTag: ${{ variables.ImageTag }}
            PoolName: $(windowsDeployAgentsNodePoolName)
            PublicAcrName: $(PublicAcrName)
            Type: standard
            ValueFile: ${{ variables.ValueFile }}
            VerifyDeployment: true
            WindowsDeployAgentsNodePoolLabel: $(WindowsDeployAgentsNodePoolLabel)
    - job: DeployApimManifest
      dependsOn: DeployManifest
      displayName: DeployApimManifest
      variables:
      - group: PreProd Management Resources
      steps:
        - template: /pipeline-templates/step/deploy-helm.yml
          parameters:
            AgentCount: 2
            AzureDevopsAgentPool: '"DAS - APIM Continuous Deployment Beta"'
            AzureServiceConnection: SFA-DIG-PreProd-ARM
            ContainerImageName: ${{ variables.ContainerImageName }}
            DeploymentName: beta-azure-pipelines-apim-deploy-agent-win
            ImageTag: ${{ variables.ImageTag }}
            PoolName: $(apimDeployAgentsNodePoolName)
            PublicAcrName: $(PublicAcrName)
            Type: apim
            ValueFile: ${{ variables.ValueFile }}
            VerifyDeployment: true
            WindowsDeployAgentsNodePoolLabel: $(ApimDeployAgentsNodePoolLabel)
  - stage: DeployProd
    dependsOn: DeployPreProd
    condition: and(succeeded(), eq(variables['resources.pipeline.image-build.sourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      variables:
      - group: PROD Management Resources
      steps:
        - template: /pipeline-templates/step/deploy-helm.yml
          parameters:
            AgentCount: 20
            AzureDevopsAgentPool: '"DAS - Continuous Deployment Agents"'
            AzureServiceConnection: SFA-DIG-Prod-ARM
            ContainerImageName: ${{ variables.ContainerImageName }}
            DeploymentName: azure-pipelines-deploy-agent-win
            ImageTag: ${{ variables.ImageTag }}
            PoolName: $(windowsDeployAgentsNodePoolName)
            PublicAcrName: $(PublicAcrName)
            Type: standard
            ValueFile: ${{ variables.ValueFile }}
            VerifyDeployment: true
            WindowsDeployAgentsNodePoolLabel: $(WindowsDeployAgentsNodePoolLabel)
    - job: DeployApimManifest
      dependsOn: DeployManifest
      displayName: DeployApimManifest
      variables:
      - group: PROD Management Resources
      steps:
        - template: /pipeline-templates/step/deploy-helm.yml
          parameters:
            AgentCount: 20
            AzureDevopsAgentPool: '"DAS - APIM Continuous Deployment Agents"'
            AzureServiceConnection: SFA-DIG-Prod-ARM
            ContainerImageName: ${{ variables.ContainerImageName }}
            DeploymentName: azure-pipelines-apim-deploy-agent-win
            ImageTag: ${{ variables.ImageTag }}
            PoolName: $(apimDeployAgentsNodePoolName)
            PublicAcrName: $(PublicAcrName)
            Type: standard
            ValueFile: ${{ variables.ValueFile }}
            VerifyDeployment: true
            WindowsDeployAgentsNodePoolLabel: $(ApimDeployAgentsNodePoolLabel)
