trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Windows/Deploy/Deployment"
    exclude:
      - "*"

pr:
  paths:
    include:
      - "Windows/Deploy/Deployment"

pool:
  name: DAS - Continuous Integration Agents

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.73
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: image-build
    source: das-azure-pipelines-agents-win-deploy (Image Build)
    branch: master
    trigger:
      branches:
        - master

variables:
- group: RELEASE das-azure-pipelines-agent
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-deploy-agent-win
- name: ImageTag
  value: $(resources.pipeline.image-build.runName)

stages:
  - stage: DeployPreProd
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      variables:
      - group: PreProd Management Resources
      - name: AgentCount
        value: 2
      - name: AzureDevopsAgentPool
        value: DAS - Continuous Deployment Beta
      - name: DeploymentName
        value: beta-azure-pipelines-deploy-agent-win
      steps:
        - template: /pipeline-templates/step/deploy(no-keda).yml
          parameters:
            VerifyDeployment: true
            Directory: $(System.DefaultWorkingDirectory)/Windows/Deploy/Deployment
            AzureServiceConnection: SFA-DIG-PreProd-ARM
    - job: DeployApimManifest
      dependsOn: DeployManifest
      displayName: DeployApimManifest
      variables:
      - group: PreProd Management Resources
      - name: AgentCount
        value: 2
      - name: AzureDevopsAgentPool
        value: DAS - APIM Continuous Deployment Beta
      - name: DeploymentName
        value: beta-azure-pipelines-apim-deploy-agent-win
      - name: WindowsDeployAgentsNodePoolLabel
        value: $(ApimDeployAgentsNodePoolLabel)
      steps:
        - template: /pipeline-templates/step/deploy(no-keda).yml
          parameters:
            VerifyDeployment: true
            Directory: $(System.DefaultWorkingDirectory)/Windows/Deploy/Deployment
            AzureServiceConnection: SFA-DIG-PreProd-ARM
  - stage: DeployProd
    dependsOn: DeployPreProd
    condition: and(succeeded(), eq(variables['resources.pipeline.image-build.sourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
    - job: DeployManifest
      displayName: DeployManifest
      variables:
      - group: PROD Management Resources
      - name: AgentCount
        value: 20
      - name: AzureDevopsAgentPool
        value: DAS - Continuous Deployment Agents
      - name: DeploymentName
        value: azure-pipelines-deploy-agent-win
      steps:
        - template: /pipeline-templates/step/deploy(no-keda).yml
          parameters:
            VerifyDeployment: true
            Directory: $(System.DefaultWorkingDirectory)/Windows/Deploy/Deployment
            AzureServiceConnection: SFA-DIG-Prod-ARM
    - job: DeployApimManifest
      dependsOn: DeployManifest
      displayName: DeployApimManifest
      variables:
      - group: PROD Management Resources
      - name: AgentCount
        value: 20
      - name: AzureDevopsAgentPool
        value: DAS - APIM Continuous Deployment Agents
      - name: DeploymentName
        value: azure-pipelines-apim-deploy-agent-win
      - name: WindowsDeployAgentsNodePoolLabel
        value: $(ApimDeployAgentsNodePoolLabel)
      steps:
        - template: /pipeline-templates/step/deploy(no-keda).yml
          parameters:
            VerifyDeployment: true
            Directory: $(System.DefaultWorkingDirectory)/Windows/Deploy/Deployment
            AzureServiceConnection: SFA-DIG-Prod-ARM