apiVersion: apps/v1
kind: Deployment
metadata:
  name: __DeploymentName__
  namespace: __AgentNameSpace__
spec:
  progressDeadlineSeconds: 1200
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: __DeploymentName__
  template:
    metadata:
      labels:
        app: __DeploymentName__
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: In
                    values:
                      - __WindowsDeployAgentsNodePoolLabel__
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - __DeploymentName__
                topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - name: __DeploymentName__
        image: __PublicAcrName__.azurecr.io/__ContainerImageName__:__ImageTag__
        command: ["powershell"]
        args: ["./start.ps1"]
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 270m
            memory: 256Mi
          limits: 
            cpu: 2500m
            memory: 2256Mi
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azp
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azp
                key: AZP_TOKEN
          - name: AZP_POOL
            value: __AzureDevopsAgentPool__
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - mountPath: /azptmp
          name: azp-tmp-volume
      tolerations:
        - key: agent-os
          operator: Equal
          value: windows
          effect: NoSchedule
      volumes:
      - name: azp-tmp-volume
        emptyDir:
          sizeLimit: 30Gi
