resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.17
    endpoint: SFA

trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Linux/Base_Ubuntu18/*"
    exclude:
      - "*"

schedules:
- cron: "0 6 * * Tue"
  displayName: Weekly Tuesday morning build
  branches:
    include:
    - master
  always: true

pr: none

pool:
  vmImage: "Ubuntu-16.04"

variables:
  - group : Release Management Resources


steps:
  - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
    parameters:
       ContainerRegistryName: $(PublicAcrName)
       ServiceConnection: SFA-DIG-Prod-ARM
       ImageName: das-azure-pipelines-build-agent

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      Contents: |
        Linux/Build_Ubuntu18/manifest.yml
      TargetFolder: "$(build.artifactstagingdirectory)/publish"
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)/publish"
