trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Windows/Deploy/Image"
    exclude:
      - "*"

pr:
  paths:
    include:
      - "Windows/Deploy/Image"

pool:
  name: DAS - Continuous Integration Agents

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.73
    endpoint: SkillsFundingAgency

schedules:
- cron: "0 3 * * Wed"
  displayName: Weekly Wednesday morning run
  branches:
    include:
    - master
  always: true

variables:
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-deploy-agent-win
jobs:
- job: ImageBuild
  timeoutInMinutes: 120
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks
  - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
    parameters:
      ContainerRegistryName: $(PublicAcrName)
      ServiceConnection: SFA-DIG-Prod-ARM
      ImageName: $(ContainerImageName)
      BranchToCreateLatestTag: master
      Platform: windows
      WorkingDirectory: Windows/Deploy/Image
