apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-pipelines-build-agent
spec:
  replicas: __agentCount__
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: azure-pipelines-build-agent
  template:
    metadata:
      labels:
        app: azure-pipelines-build-agent
    spec:
      terminationGracePeriodSeconds: 300
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - __agentPoolName__
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - azure-pipelines-build-agent
              topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
        - name: azure-pipelines-build-agent
          image: apprenticeshipsdevops/azure-pipelines-build-agent:__ImageVersion__
          env:
            - name: VSTS_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: vsts
                  key: VSTS_ACCOUNT
            - name: VSTS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vsts
                  key: VSTS_TOKEN
            - name: VSTS_POOL
              value: DAS - Continuous Integration
            - name: NUGET_PACKAGES
              value: "/mnt/nugetcache/packages"
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-volume
            - mountPath: "/mnt/nugetcache"
              name: nuget-cache
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
        - name: nuget-cache
          hostPath:
            path: /var/nugetcache
            type: DirectoryOrCreate