trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Windows/Build-Base/*"
    exclude:
      - "*"
    
pr: none

schedules:
  - cron: "0 4 8-14 * Wed"
    displayName: Monthly updates build
    branches:
      include:
        - master
    always: true

resources:
  repositories:
    - repository: self
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/0.4.13
      endpoint: SkillsFundingAgency

pool:
  name: DAS - Continuous Integration Agents

variables:
- group: Release Management Resources
- name: ContainerImageName
  value: azure-pipelines-base-build-agent-win

steps:
- template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
  parameters:
    ContainerRegistryName: $(PublicAcrName)
    ServiceConnection: SFA-DIG-Prod-ARM
    ImageName: $(ContainerImageName)
    BranchToCreateLatestTag: master
    Platform: windows
    WorkingDirectory: $(Build.SourcesDirectory)/Windows/Build-Base
    
