trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Configuration/*"
    exclude:
      - "*"

pr: none

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - script: docker run -t -v `pwd`/Configuration:/Configuration garethr/kubeval -d "Configuration/rbac"
    displayName: Validate manifests

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      Contents: |
        Configuration/**
      TargetFolder: "$(build.artifactstagingdirectory)/publish"
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)/publish"
