trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Linux/Ubuntu-20-Build/*"
    exclude:
      - "*"

pr: none

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.24
    endpoint: SFA

schedules:
- cron: "0 6 * * Tue"
  displayName: Weekly Tuesday morning build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

variables:
- group : Release Management Resources

steps:
  - template: azure-pipelines-templates/deploy/step/tokenize-files.yml@das-platform-building-blocks
    parameters:
      WorkingDirectory: Linux/Ubuntu-20-Build
      TargetFiles: Dockerfile
      TokenPrefix: __
      TokenSuffix: __

  - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
    parameters:
      ContainerRegistryName: $(PublicAcrName)
      ServiceConnection: SFA-DIG-Prod-ARM
      ImageName: azure-pipelines-build-agent-ubuntu-20
      WorkingDirectory: Linux/Ubuntu-20-Build
      BranchToCreateLatestTag: master

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      Contents: |
        Linux/Ubuntu-20-Build/manifest.yml
      TargetFolder: "$(build.artifactstagingdirectory)/publish"
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)/publish"

