trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - pipeline-templates/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile
    exclude:
      - "*"

pr: none

pool:
  vmImage: "Ubuntu-16.04"

variables:
  - group : Release Management Resources

steps:
  - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
    parameters:
      ContainerRegistryName: $(PublicAcrName)
      ServiceConnection: SFA-DIG-Prod-ARM
      ImageName: das-azure-pipelines-build-agent

  - task: CopyFiles@2
    displayName: "Copy Files to: $(build.artifactstagingdirectory)"
    inputs:
      Contents: |
        Linux/Build_Ubuntu20/manifest.yml
      TargetFolder: "$(build.artifactstagingdirectory)/publish"
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)/publish"

