trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - "Linux/Ubuntu-18/Base/*"
    exclude:
      - "*"

schedules:
- cron: "0 6 * * Tue"
  displayName: Weekly Tuesday morning build
  branches:
    include:
    - master
  always: true

pr: none

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.22
    endpoint: SFA

pool:
  name: DAS - Continuous Integration
  demands: Agent.OS -equals Windows_NT

variables:
- group : Release Management Resources

steps:
  - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
    parameters:
      ContainerRegistryName: $(PublicAcrName)
      ServiceConnection: SFA-DIG-Prod-ARM
      ImageName: azure-pipelines-base-build-agent-ubuntu-18
      WorkingDirectory: Linux/Ubuntu-18/Base
      BranchToCreateLatestTag: DASD-8851-ubuntu-18-20-build-agents.2
